# Generated by Django 3.2.4 on 2021-08-04 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flow_docs', '0002_document_viewers'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Viewers',
            new_name='Viewer',
        ),
    ]
